---
name: GitHub Actions Pipeline for a Flask App

on:
  push:
    branches:
    - monday-practice
  pull_request:
    branches:
    - main

jobs:
  scan:
    name: GitLeaks scan for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}










