---
name: GitHub Actions Pipeline for a Flask App

on:
  push:
    branches:
    - monday-practice
  pull_request:
    branches:
    - main

jobs:
  scan:
    name: GitLeaks scan for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2.3.7

  editorconfig:
    name: EditorConfig checker and Markdownlint CLI
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run EditorConfig Checker 
        run: editorconfig-checker

      - name: Install Markdownlint CLI
        run: npm install -g markdownlint-cli
      
      - name: Run Markdownlint  
        run: markdownlint **/*.md

  python-black-pylint:
    name: Run Python Black and Pylint checks
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Python Black Check
        uses: rodrigogiraoserrao/python-black-check@v3.0
        with:
          line-length: '81'
      
      - name: Run PylintPylint GitHub Action
        uses: ReasonSoftware/action-pylint@v2.0.3
        with:
          requirements_file: requirements.txt
          filepaths: "app/*.py"
          options: "-d C0114,C0115,C0116"

  unittest-snyk-sonar:
    name: Run Python unit tests, Snyk, and Sonar
    runs-on: ubuntu-latest
    needs: [scan, editorconfig, python-black-pylint]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover -s app -p "*.py"

      - name: Run Snyk
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        with:
          args:
            -Dsonar.organization=fannymalinova
            -Dsonar.projectKey=FannyMalinova_devops-programme
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_SECRET }}

  docker:
    name: Docker build
    runs-on: ubuntu-latest
    needs: [unittest-snyk-sonar]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}

          
          












